package(default_visibility = ["//visibility:public"])

filegroup(
    name = "test_data",
    srcs = [
        "analyze_perturbation_result_205_33_4a_2_4.txtpb",
        "processed_tables_205_33_4a_2_4.txtpb",
    ],
)
