package(default_visibility = ["//visibility:public"])

filegroup(
    name = "msg_info_table",
    srcs = ["msg_number_label_si_genpos.txt"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "lattice_type_space_group_number",
    srcs = ["lattice_type_space_group_number.txt"],
    visibility = ["//visibility:public"],
)
